In [90]:
from pyforest import *

In [105]:
data = pd.read_excel('august.xlsx')

In [106]:
data.columns = data.iloc[0]

In [107]:
data

,Time,27T1 (MVA),27T2 (MVA),Total Station Load (MVA),Time,27T1 (MVA),27T2 (MVA),Total Station Load (MVA),Time,27T1 (MVA),...,27T2 (MVA),Total Station Load (MVA),Time,27T1 (MVA),27T2 (MVA),Total Station Load (MVA),Time,27T1 (MVA),27T2 (MVA),Total Station Load (MVA)
0,Time,27T1 (MVA),27T2 (MVA),Total Station Load (MVA),Time,27T1 (MVA),27T2 (MVA),Total Station Load (MVA),Time,27T1 (MVA),...,27T2 (MVA),Total Station Load (MVA),Time,27T1 (MVA),27T2 (MVA),Total Station Load (MVA),Time,27T1 (MVA),27T2 (MVA),Total Station Load (MVA)
1,2015-04-01 01:00:00,9.2,6.5,15.7,01:00:00,10.6,7.5,18.1,2015-04-01 01:00:00,10.4,...,7.8,18.4,2015-04-01 01:00:00,10.8,7.2,18,2015-04-01 01:00:00,10.6,7.3,17.9
2,2015-04-01 02:00:00,8.8,6.1,14.9,2015-04-01 02:00:00,10,7.1,17.1,2015-04-01 02:00:00,10.3,...,7.6,18,2015-04-01 02:00:00,10.3,6.8,17.1,2015-04-01 02:00:00,10.5,7,17.5
3,2015-04-01 03:00:00,8.7,6.1,14.8,2015-04-01 03:00:00,9.9,6.9,16.8,2015-04-01 03:00:00,10.5,...,7.4,17.4,2015-04-01 03:00:00,10.3,6.5,16.8,2015-04-01 03:00:00,10.5,7,17.5
4,2015-04-01 04:00:00,8.7,6.1,14.8,2015-04-01 04:00:00,9.9,7,16.9,2015-04-01 04:00:00,10.3,...,7,16.8,2015-04-01 04:00:00,9.8,6.5,16.3,2015-04-01 04:00:00,10.6,7.1,17.7
5,2015-04-01 05:00:00,9.8,6.5,16.3,2015-04-01 05:00:00,9.9,7.1,17,2015-04-01 05:00:00,9.7,...,7.1,16.8,2015-04-01 05:00:00,10.5,7.2,17.7,2015-04-01 05:00:00,10.9,7.2,18.1
6,2015-04-01 06:00:00,9.1,5.9,15,2015-04-01 06:00:00,10.6,7.5,18.1,2015-04-01 06:00:00,10.5,...,7.1,16.7,2015-04-01 06:00:00,9.6,6.8,16.4,2015-04-01 06:00:00,9.8,6.5,16.3
7,2015-04-01 07:00:00,9,5.9,14.9,2015-04-01 07:00:00,9.3,6.8,16.1,2015-04-01 07:00:00,9.2,...,6.6,15.7,2015-04-01 07:00:00,9.5,6.6,16.1,2015-04-01 07:00:00,9.2,6.2,15.4
8,2015-04-01 08:00:00,9.3,6.4,15.7,2015-04-01 08:00:00,9.3,6.7,16,2015-04-01 08:00:00,8.4,...,6.7,15.7,2015-04-01 08:00:00,9.5,6.5,16,2015-04-01 08:00:00,9.7,6.3,16
9,2015-04-01 09:00:00,9.4,6.5,15.9,2015-04-01 09:00:00,8.6,6.9,15.5,2015-04-01 09:00:00,8.3,...,6.9,15,2015-04-01 09:00:00,9.7,5.6,15.3,2015-04-01 09:00:00,8.4,5.8,14.2
10,2015-04-01 10:00:00,7.7,6.8,14.5,2015-04-01 10:00:00,9.5,6.9,16.4,2015-04-01 10:00:00,7.9,...,7.1,16.4,2015-04-01 10:00:00,8.8,6.3,15.1,2015-04-01 10:00:00,7.8,5.6,13.4
11,2015-04-01 11:00:00,8.2,6.9,15.1,2015-04-01 11:00:00,9.4,7,16.4,2015-04-01 11:00:00,6.4,...,7.2,16.7,2015-04-01 11:00:00,9.2,6.9,16.1,2015-04-01 11:00:00,8.2,5.9,14.1
12,2015-04-01 12:00:00,9.1,6.9,16,2015-04-01 12:00:00,9.3,6.9,16.2,2015-04-01 12:00:00,7.1,...,7.2,16.7,2015-04-01 12:00:00,9.5,7.1,16.6,2015-04-01 12:00:00,8.5,6,14.5
13,2015-04-01 13:00:00,9.4,6.9,16.3,2015-04-01 13:00:00,9.2,6.7,DUKE,2015-04-01 13:00:00,7.2,...,7,16.4,2015-04-01 13:00:00,8.7,6.4,15.1,2015-04-01 13:00:00,8.7,5.9,14.6
14,2015-04-01 14:00:00,9.6,7.3,16.9,2015-04-01 14:00:00,8.9,6.6,15.5,2015-04-01 14:00:00,6.8,...,6.9,16.4,2015-04-01 14:00:00,8.7,7.2,15.9,2015-04-01 14:00:00,8.9,6.1,15
15,2015-04-01 15:00:00,9.1,7.3,16.4,2015-04-01 15:00:00,8.8,6.6,15.4,2015-04-01 15:00:00,8,...,7.3,17,2015-04-01 15:00:00,8.9,6.9,15.8,2015-04-01 15:00:00,8.8,6.2,15
16,2015-04-01 16:00:00,9.6,7.3,16.9,2015-04-01 16:00:00,8.9,6.6,15.5,2015-04-01 16:00:00,8,...,7.6,18.3,2015-04-01 16:00:00,10.1,7.6,17.7,2015-04-01 16:00:00,9,6.2,15.2
17,2015-04-01 17:00:00,10.2,7,17.2,2015-04-01 17:00:00,9.4,6.5,15.9,2015-04-01 17:00:00,8.3,...,6.6,15.8,2015-04-01 17:00:00,9.6,6.9,16.5,2015-04-01 17:00:00,9.2,6.4,15.6
18,2015-04-01 18:00:00,10.8,7.4,18.2,2015-04-01 18:00:00,9.1,6.2,DANSO,2015-04-01 18:00:00,8.6,...,6.4,15.8,2015-04-01 18:00:00,11,7.6,18.6,2015-04-01 18:00:00,10.3,7.3,17.6
19,18:15:00,11.3,7.7,19,18:15:00,10.2,8.3,18.5,18:15:00,9.1,...,6.8,16.9,18:15:00,11.4,7.7,19.1,18:15:00,10.6,7.6,18.2
20,2015-04-01 18:30:00,11.4,8.2,19.6,2015-04-01 18:30:00,11.9,8.6,20.5,2015-04-01 18:30:00,9.7,...,7.8,18.9,2015-04-01 18:30:00,11.7,8.2,19.9,2015-04-01 18:30:00,11.4,8.2,19.6
21,18:45:00,12.6,9.1,21.7,18:45:00,12.9,9.3,22.2,18:45:00,11,...,8.5,20.7,18:45:00,12.4,8.4,20.8,18:45:00,12.5,8.8,21.3
22,2015-04-01 19:00:00,12.3,8.8,21.1,2015-04-01 19:00:00,13.4,9.3,22.7,2015-04-01 19:00:00,11.9,...,8.8,21.5,2015-04-01 19:00:00,12.9,8.6,21.5,2015-04-01 19:00:00,12.7,9,21.7
23,19:15:00,13.2,9.7,22.9,19:15:00,13.4,9.3,22.7,19:15:00,11.9,...,9.1,22.1,19:15:00,13.3,8.9,22.2,19:15:00,12,9.2,21.2
24,2015-04-01 19:30:00,13.2,9.9,23.1,2015-04-01 19:30:00,13.7,9.5,23.2,2015-04-01 19:30:00,12.3,...,9,22.1,2015-04-01 19:30:00,13.6,9.2,22.8,2015-04-01 19:30:00,12.9,9.2,22.1
25,19:45:00,13.2,9.7,22.9,19:45:00,13.5,9.6,23.1,19:45:00,12.4,...,9.7,23.5,19:45:00,14.2,9.6,23.8,19:45:00,12.9,9.3,22.2
26,2015-04-01 20:00:00,13.3,9.6,22.9,2015-04-01 20:00:00,13.6,9.6,23.2,2015-04-01 20:00:00,12.5,...,9.1,22.1,2015-04-01 20:00:00,14.1,9.7,23.8,2015-04-01 20:00:00,12.9,9.2,22.1
27,20:15:00,13.3,9.6,22.9,20:15:00,13.6,9.5,23.1,20:15:00,12.4,...,9.1,22.1,20:15:00,14.2,9.7,23.9,20:15:00,NaN,NaN,0
28,2015-04-01 21:00:00,13.2,9.8,23,2015-04-01 21:00:00,13.5,9.5,23,2015-04-01 21:00:00,12,...,9.1,22.1,2015-04-01 21:00:00,13.5,9.3,22.8,2015-04-01 21:00:00,NaN,NaN,0
29,2015-04-01 22:00:00,12.5,9.2,21.7,2015-04-01 22:00:00,12.8,9.1,21.9,2015-04-01 22:00:00,12,...,9.1,22.1,2015-04-01 22:00:00,12.7,8.8,21.5,2015-04-01 22:00:00,NaN,NaN,0
30,2015-04-01 23:00:00,11.2,8.3,19.5,2015-04-01 23:00:00,12.1,8.2,20.3,2015-04-01 23:00:00,10.9,...,8.9,21.7,2015-04-01 23:00:00,11.2,7.8,19,2015-04-01 23:00:00,NaN,NaN,0
31,2015-04-02 00:00:00,10.3,7.7,18,2015-04-02 00:00:00,10.6,7.6,18.2,2015-04-02 00:00:00,10.7,...,8.5,21.2,2015-04-02 00:00:00,10.9,7.4,18.3,2015-04-02 00:00:00,NaN,NaN,0
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [108]:
data.drop(0, inplace=True)

In [109]:
data['Total Station Load (MVA)']

,Total Station Load (MVA),Total Station Load (MVA),Total Station Load (MVA),Total Station Load (MVA),Total Station Load (MVA),Total Station Load (MVA),Total Station Load (MVA),Total Station Load (MVA),Total Station Load (MVA),Total Station Load (MVA),...,Total Station Load (MVA),Total Station Load (MVA),Total Station Load (MVA),Total Station Load (MVA),Total Station Load (MVA),Total Station Load (MVA),Total Station Load (MVA),Total Station Load (MVA),Total Station Load (MVA),Total Station Load (MVA)
1,15.7,18.1,17.7,18.2,18,17.5,17.9,15.6,16.1,14.9,...,16,17.6,15.7,14.6,15.7,15.8,17.4,18.4,18,17.9
2,14.9,17.1,17.4,17.8,17.6,16.6,17.6,15.4,15.5,14.8,...,15.6,17.3,15.5,14.4,15.2,15.4,17.2,18,17.1,17.5
3,14.8,16.8,17.4,17,17.2,16.6,17.3,15.4,15.4,14.7,...,15.2,17.6,15.3,14.4,15.2,15.1,17.1,17.4,16.8,17.5
4,14.8,16.9,17.2,16.7,17,17.5,17.3,15.4,15.7,14.7,...,15.2,17.7,15.4,14.4,15.2,15,17,16.8,16.3,17.7
5,16.3,17,16.3,16.6,16.4,15.7,17.4,15.6,16.1,14.8,...,15.7,18.4,15.7,14.4,15.3,15.1,17,16.8,17.7,18.1
6,15,18.1,17.1,16.2,15.3,16.4,17.4,15.7,15.7,15.3,...,17.1,16.9,15.8,14.5,15.8,16,16.2,16.7,16.4,16.3
7,14.9,16.1,15.2,16.1,14.6,16.1,16.1,14.9,15,14,...,16,16.1,14.7,15.2,14.8,15.8,15.6,15.7,16.1,15.4
8,15.7,16,14.5,16.1,14.9,15.5,15.6,15.6,14.9,13.8,...,16.2,16.5,14.5,15.5,15.2,15,15.4,15.7,16,16
9,15.9,15.5,14.1,13.7,14,16.4,15.8,16.3,15.7,14.9,...,16.1,16.4,12.9,15,16.3,15.4,15.6,15,15.3,14.2
10,14.5,16.4,13.6,12.4,14,16.5,16.6,16.4,15.8,15.5,...,16.2,16.5,12.7,13.7,16.5,15.8,16.6,16.4,15.1,13.4
11,15.1,16.4,12.1,12.3,13.6,17.1,15.8,16.5,15.9,15,...,16.4,16.4,12.4,13.8,16.7,16,16.2,16.7,16.1,14.1
12,16,16.2,12.7,12.4,13.6,16.4,15.3,16.6,15.3,15.2,...,16.6,16.8,12.5,14.1,16.9,16.3,16.2,16.7,16.6,14.5
13,16.3,DUKE,12.7,13,13.9,15.6,14.4,17,15.8,15.5,...,16.2,16.5,12.5,15.2,15.5,16.8,12.4,16.4,15.1,14.6
14,16.9,15.5,12.5,13.6,13.9,15.7,15.2,16.9,15.2,15.9,...,16.5,16.3,12.5,15.5,15.4,17.2,14.9,16.4,15.9,15
15,16.4,15.4,13.8,13.9,14.8,17,16.1,16.5,16.3,15.6,...,17.2,16.2,12.5,16.1,16.8,17.6,17.2,17,15.8,15
16,16.9,15.5,13.8,14.2,14.8,17.7,16.7,17.1,16.3,16,...,17.7,16.6,12.5,15,17.7,16,19.6,18.3,17.7,15.2
17,17.2,15.9,14.2,14.2,15.1,16.2,16.6,17.2,16.8,15.3,...,15.9,16.9,15.4,15.5,16.6,15.2,15.7,15.8,16.5,15.6
18,18.2,DANSO,14.7,16.2,16.3,16,17,17.6,17.9,17.2,...,16.4,18.1,17,16.7,18.1,15.6,16.4,15.8,18.6,17.6
19,19,18.5,15.3,17,16.5,16.6,18.8,18.4,18.1,17.8,...,16.9,18.3,17.1,17.8,18.4,16.2,17.4,16.9,19.1,18.2
20,19.6,20.5,16.8,17.5,17.8,17.6,19.8,20.3,20.5,18.4,...,19.1,21.3,19,21,21.2,19,19.4,18.9,19.9,19.6
21,21.7,22.2,19.1,19.2,19.7,20.3,21.4,22.1,21.9,23.3,...,20.9,22.5,19.7,22.1,23,20.6,20.9,20.7,20.8,21.3
22,21.1,22.7,20.5,20.6,20.8,21.6,22.6,23,22.8,23.3,...,21.5,22.9,21.5,23,23.1,21.1,21.3,21.5,21.5,21.7
23,22.9,22.7,20.6,20.9,21.1,22.1,23.1,22.9,22.6,23.7,...,21.9,23.2,22.3,22.9,23.2,21.6,21.7,22.1,22.2,21.2
24,23.1,23.2,21.2,21.4,21.6,22,23,23.1,22.9,23.8,...,22.1,23.4,22.5,23,23.4,21.9,21.6,22.1,22.8,22.1
25,22.9,23.1,21.3,21.5,21.7,22.2,23.4,23.3,23.1,23.8,...,22.2,23.3,22.1,23.2,22.5,22.2,21.9,23.5,23.8,22.2
26,22.9,23.2,21.6,21.9,22,22.2,23.6,23.6,23.1,23.7,...,22.5,23.5,22.2,23.2,23.4,22,21.7,22.1,23.8,22.1
27,22.9,23.1,21.3,21.5,22,22.2,23.3,22.6,23.2,23.9,...,24,21.7,20.9,23,23.4,22.8,22.9,22.1,23.9,0
28,23,23,21.5,22.9,21.8,22.1,21.7,21.3,21,22.3,...,23.6,21.5,19.7,21.4,21.7,23.7,22.6,22.1,22.8,0
29,21.7,21.9,20.9,20.7,21.4,22.2,20.3,20,19.9,21.5,...,20.8,19.5,18,19.5,19.4,21.9,21.4,22.1,21.5,0
30,19.5,20.3,18.9,18.9,20.8,18.3,17.7,18.4,18,19.5,...,19.7,17.4,16.7,17.8,17.9,19.5,19.5,21.7,19,0
31,18,18.2,18.5,18.4,20,18.2,16.8,16.9,16.4,17.4,...,17.6,16.5,15.6,16.5,16.5,17.6,19,21.2,18.3,0
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [110]:
data['Total Station Load (MVA)'].to_excel('august_load.xlsx')

In [50]:
january_load = pd.read_excel('total station load.xlsx')

In [63]:
january_load

,Hour,1,2,3,4,5,6,7,8,9,...,22,23,24,25,26,27,28,29,30,31
0,1.00,39.7,23.6,28.0,34.8,31.8,32.3,32.6,34.3,34.4,...,37.4,36.0,35.6,41.3,39.9,37.8,35.4,37.8,38.2,42.4
1,2.00,38.8,23.5,27.2,34.2,30.7,31.6,30.7,33.2,33.8,...,36.0,34.7,34.8,40.6,38.8,34.3,34.9,36.8,37.0,41.3
2,3.00,38.1,23.0,26.6,32.6,30.4,31.3,30.8,32.8,33.4,...,35.2,34.0,34.4,40.0,38.4,33.4,21.1,35.8,39.0,40.4
3,4.00,37.7,23.3,26.0,30.2,30.7,31.6,30.5,32.8,32.4,...,35.0,34.9,33.7,40.2,37.5,34.1,34.6,35.4,39.0,42.1
4,5.00,38.9,24.0,26.0,31.3,31.2,32.0,30.9,33.9,32.4,...,36.8,36.7,35.9,40.8,37.5,35.3,34.8,37.6,40.9,42.2
5,6.00,42.5,24.4,26.4,32.3,31.3,33.9,32.2,36.2,34.1,...,40.4,41.2,40.9,42.4,39.1,37.6,35.9,39.7,41.4,42.1
6,7.00,35.6,24.0,24.8,30.2,29.0,35.9,31.2,34.7,33.0,...,32.0,33.6,33.7,35.7,37.5,40.1,31.1,32.2,35.4,35.0
7,8.00,32.5,24.1,23.7,29.9,28.8,34.1,30.6,32.9,32.4,...,29.3,29.6,30.1,31.8,34.8,36.1,29.5,29.4,31.4,31.6
8,9.00,32.4,0.0,19.1,30.5,11.5,11.9,30.1,32.9,32.0,...,30.0,29.0,30.3,0.0,0.0,30.3,29.5,29.4,31.6,32.5
9,10.00,33.3,0.0,30.6,31.5,11.4,10.7,29.7,31.0,32.5,...,30.5,29.5,30.1,10.5,10.4,29.1,30.3,29.1,32.5,33.0
10,11.00,33.7,9.2,30.4,31.4,11.7,10.7,27.4,32.6,32.7,...,31.0,29.9,30.7,11.2,11.1,29.8,30.6,29.6,32.8,33.8
11,12.00,34.7,9.5,30.3,31.4,11.8,10.8,28.0,32.9,32.6,...,30.7,29.2,31.1,11.3,11.3,30.4,31.1,30.2,35.8,33.6
12,13.00,34.8,9.7,30.9,30.6,12.1,11.3,28.0,33.2,33.4,...,28.3,27.9,32.1,11.3,11.4,29.1,30.5,30.5,35.4,33.6
13,14.00,34.9,0.0,31.5,30.2,12.1,12.1,29.6,33.3,33.2,...,28.7,29.2,32.0,11.4,11.4,27.8,31.4,0.0,29.3,33.6
14,15.00,0.0,9.8,32.4,31.1,12.5,12.6,29.6,34.8,35.2,...,30.6,29.8,33.6,11.7,11.4,33.4,28.2,36.0,32.0,34.8
15,16.00,36.7,10.0,32.8,31.4,13.0,13.0,30.8,35.6,36.3,...,32.0,33.5,35.0,12.0,11.6,34.4,33.0,32.7,34.3,36.4
16,17.00,36.4,10.5,32.8,31.7,13.5,13.5,35.2,35.8,36.5,...,33.9,34.8,35.3,11.9,12.1,34.8,33.8,34.6,35.0,36.3
17,18.00,37.4,11.3,34.5,34.0,35.4,40.5,37.3,38.3,36.1,...,36.0,36.1,37.0,42.9,12.3,36.7,35.8,39.1,38.0,38.6
18,18.15,39.5,12.2,37.8,38.1,43.2,38.7,41.8,42.7,39.0,...,37.3,36.9,38.7,39.5,0.0,38.1,37.3,41.1,38.4,40.3
19,18.30,43.0,34.1,41.4,40.9,47.6,44.1,40.3,44.7,41.7,...,42.5,40.4,42.3,43.2,0.0,43.3,41.4,42.9,42.3,43.4
20,18.45,45.4,34.8,43.3,42.3,49.5,45.3,42.2,42.8,43.1,...,44.8,43.7,44.4,25.2,0.0,44.7,44.9,44.7,44.9,45.9
21,19.00,46.8,34.2,43.9,43.2,49.6,44.8,43.3,44.1,44.3,...,45.6,45.0,45.8,50.2,51.4,46.0,45.5,46.7,45.6,47.3
22,19.15,45.6,27.9,44.3,44.0,48.3,45.3,43.7,44.5,44.5,...,45.9,46.2,46.8,47.1,52.7,42.8,46.5,46.8,47.8,48.3
23,19.30,47.3,38.8,44.0,44.2,40.7,45.6,44.4,44.5,44.8,...,45.9,45.8,47.1,26.2,45.2,46.9,47.9,47.0,46.8,48.0
24,19.45,47.7,39.5,44.2,44.5,44.9,45.2,44.4,44.7,45.0,...,46.5,47.3,47.5,26.4,46.1,47.6,49.5,47.1,47.8,48.2
25,20.00,47.4,31.8,44.0,44.2,44.8,43.8,44.6,44.4,45.2,...,47.4,47.3,48.1,26.3,43.5,47.5,48.9,47.9,47.8,47.4
26,20.15,41.2,33.0,44.5,43.7,45.1,44.9,44.3,44.8,45.0,...,47.0,46.9,48.4,27.1,43.5,45.0,46.6,47.1,48.1,48.3
27,21.00,34.1,33.2,42.2,43.2,44.0,44.2,42.6,39.7,44.0,...,47.4,45.7,47.5,54.2,53.0,47.9,47.1,44.2,47.7,47.5
28,22.00,23.1,31.3,39.3,39.4,40.4,41.2,42.5,33.1,39.0,...,43.4,42.9,46.1,46.8,45.9,45.7,43.8,45.7,44.6,46.7
29,23.00,23.9,31.1,35.9,35.2,35.8,36.7,38.8,31.9,36.5,...,40.0,40.1,45.2,42.6,41.5,39.3,40.5,40.3,43.2,43.8
30,24.00,23.3,30.8,35.2,32.7,33.6,33.9,35.9,31.3,35.4,...,37.0,37.8,44.5,41.2,0.0,37.1,39.6,39.6,43.6,41.4

In [83]:
df = {}
for i in range(1,32):
    frame = {'Day'}
    df[i] = pd.concat([january_load[['Hour',i]],i])

TypeError: cannot concatenate object of type '<class 'int'>'; only Series and DataFrame objs are valid

In [71]:
df[31]

     Hour    31
0    1.00  42.4
1    2.00  41.3
2    3.00  40.4
3    4.00  42.1
4    5.00  42.2
5    6.00  42.1
6    7.00  35.0
7    8.00  31.6
8    9.00  32.5
9   10.00  33.0
10  11.00  33.8
11  12.00  33.6
12  13.00  33.6
13  14.00  33.6
14  15.00  34.8
15  16.00  36.4
16  17.00  36.3
17  18.00  38.6
18  18.15  40.3
19  18.30  43.4
20  18.45  45.9
21  19.00  47.3
22  19.15  48.3
23  19.30  48.0
24  19.45  48.2
25  20.00  47.4
26  20.15  48.3
27  21.00  47.5
28  22.00  46.7
29  23.00  43.8
30  24.00  41.4

In [81]:
pd.concat([df[1], df[2]])

/home/ghaff/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.

     Hour     1     2
0    1.00  39.7   NaN
1    2.00  38.8   NaN
2    3.00  38.1   NaN
3    4.00  37.7   NaN
4    5.00  38.9   NaN
..    ...   ...   ...
26  20.15   NaN  33.0
27  21.00   NaN  33.2
28  22.00   NaN  31.3
29  23.00   NaN  31.1
30  24.00   NaN  30.8

[62 rows x 3 columns]